apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: geode-websession
build:
  artifacts:
    - image: ojhughes/geode-websession
      context: geode-gateway
      custom:
        buildCommand: |
          ../gradlew bootBuildImage --imageName="$IMAGE" && docker push "$IMAGE"
deploy:
  kustomize:

    paths:
      - k8s
