spring:
  data:
    gemfire:
      locators: localhost[10344]
      cache:
        bind-address: 0.0.0.0
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: '*'
